# Model 1 District -> Crop

In [6]:
import tensorflow_decision_forests as tfdf
import pandas as pd
import numpy as np
import tensorflow as tf

In [68]:
dataset_df = pd.read_csv("districts_vs_crops.csv")
#dataset_df.rename(columns = {'index':'dist', '0':"crop"}, inplace = True)
dataset_df = dataset_df.drop(['Unnamed: 0'], axis=1)

In [69]:
dataset_df

dist       crop
0    24 PARAGANAS NORTH   Coconut 
1    24 PARAGANAS SOUTH   Coconut 
2              ADILABAD  Sugarcane
3            AGAR MALWA  Sugarcane
4                  AGRA  Sugarcane
..                  ...        ...
641              YADGIR  Sugarcane
642         YAMUNANAGAR  Sugarcane
643               YANAM   Coconut 
644            YAVATMAL  Sugarcane
645           ZUNHEBOTO  Sugarcane

[646 rows x 2 columns]

In [29]:
dataset_df["dist"].unique()[:10]

array(['24 PARAGANAS NORTH', '24 PARAGANAS SOUTH', 'ADILABAD',
       'AGAR MALWA', 'AGRA', 'AHMADABAD', 'AHMEDNAGAR', 'AIZAWL', 'AJMER',
       'AKOLA'], dtype=object)

In [72]:
dataset_df[label].unique()

array(['Coconut ', 'Sugarcane', 'Banana', 'Tapioca', 'Potato', 'Papaya',
       'Barley', 'Tobacco', 'Onion', 'Pineapple', 'Dry chillies',
       'Sweet potato', 'Maize', 'Other Vegetables', 'Rice', 'Dry ginger'],
      dtype=object)

## train a model to that but thats optional

In [73]:
dataset_np = dataset_df.to_numpy()
print(dataset_np.shape)

(646, 2)


In [74]:
cfeat = dataset_np[:,:1]
print(cfeat.shape)
clabels = dataset_np[:,1]

(646, 1)


In [75]:
le_labels = preprocessing.LabelEncoder()
le_labels.fit(list(set(clabels)))
clabels = le_labels.transform(clabels)

le_feats = preprocessing.LabelEncoder()
le_feats.fit(cfeat[:, 0])
cfeats = le_feats.transform(cfeat)

X_train, X_test, y_train, y_test = train_test_split(
cfeats, clabels, test_size=0.33, random_state=42)

In [76]:
y_train.shape

(432,)

In [77]:
clf = RandomForestClassifier(max_depth=20, random_state=0)
clf.fit(X_train[:, np.newaxis], y_train)

RandomForestClassifier(max_depth=20, random_state=0)

In [78]:
clf.score(X_train[:, np.newaxis], y_train)

0.9976851851851852

## Add in epected yield per harvest in rupies 

In [79]:
dataset_df

dist       crop
0    24 PARAGANAS NORTH   Coconut 
1    24 PARAGANAS SOUTH   Coconut 
2              ADILABAD  Sugarcane
3            AGAR MALWA  Sugarcane
4                  AGRA  Sugarcane
..                  ...        ...
641              YADGIR  Sugarcane
642         YAMUNANAGAR  Sugarcane
643               YANAM   Coconut 
644            YAVATMAL  Sugarcane
645           ZUNHEBOTO  Sugarcane

[646 rows x 2 columns]

# Model 2 Climate Soil -> Crop

In [7]:
from sklearn import preprocessing
from sklearn import feature_extraction
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.ensemble import RandomForestClassifier

In [8]:
croprec = pd.read_csv("/home/f/F.Kiessler/makeathon/data_india/crop_recommendation_dataset/Crop_recommendation.csv")

In [9]:
crop_npy = croprec.to_numpy()
print(crop_npy.shape)

(2200, 8)


In [10]:
cfeat = crop_npy[:,:7]
print(cfeat.shape)
clabels = crop_npy[:,7]

(2200, 7)


In [11]:
le_labels = preprocessing.LabelEncoder()
le_labels.fit(list(set(clabels)))
clabels = le_labels.transform(clabels)

X_train, X_test, y_train, y_test = train_test_split(
cfeat, clabels, test_size=0.33, random_state=42)

In [12]:
clf = RandomForestClassifier(max_depth=20, random_state=0)
clf.fit(X_train, y_train)

RandomForestClassifier(max_depth=20, random_state=0)

In [13]:
clf.score(X_test, y_test)

0.9931129476584022

In [14]:
X_train[0]

array([81, 16, 45, 26.90435747, 86.25426228, 6.727468157000001,
       59.75980023], dtype=object)

In [15]:
pred = clf.predict(np.array([[83, 30, 40, 23, 90, 5, 30]]))

array([15])

In [17]:
le_labels.inverse_transform([15])


array(['muskmelon'], dtype='<U11')

# Centroids model: (latitude, longitude)->Best Crop

In [92]:
import matplotlib.pyplot as plt

In [18]:
LatLonCrop = pd.read_csv("/home/f/F.Kiessler/makeathon/data_india/dist_lat_long_crop_eff.csv")

In [45]:
crop_npy = LatLonCrop[["Latitude", "Longitude","Crop"]].to_numpy()
print(crop_npy)

[[7.835290749774195 93.5116012375786 'Coconut ']
 [19.284513950073435 78.81321233480176 'Sugarcane']
 [14.312065561843148 77.4601584478577 'Coconut ']
 ...
 [22.06238845067688 88.87793960802345 'Coconut ']
 [23.254192328767108 86.3968532876713 'Coconut ']
 [21.854427507266063 88.44536970827778 'Coconut ']]


In [46]:
cfeat = crop_npy[:,:2]
print(cfeat.shape)
clabels = crop_npy[:,2]
clabels.shape

(558, 2)


(558,)

In [47]:
le_labels = preprocessing.LabelEncoder()
le_labels.fit(list(set(clabels)))
clabels_int = le_labels.transform(clabels)

X_train, X_test, y_train, y_test = train_test_split(
cfeat, clabels_int, test_size=0.33, random_state=42)

In [85]:
clf = RandomForestClassifier(max_depth=8, random_state=0)
clf.fit(X_train, y_train)

RandomForestClassifier(max_depth=8, random_state=0)

In [87]:
X_train[0]

array([25.33959557069844, 92.37608160136298], dtype=object)

In [88]:
clf.predict(np.array([[25.21,92.24]]))

array([2])

In [89]:
le_labels.inverse_transform([13])


array(['Tapioca'], dtype='<U16')